class Closable[T]:
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def __enter__(self) -> T: ...
    def __exit__(
        self,
        exc_type: any,
        exc_value: any,
        traceback: any,
    ) -> bool | None: ...
    def __del__(self) -> None: ...
