from typing import Literal
from ._guid import GuidEnum, GUID

__all__ = ["MediaType"]

class MediaType:
    major_type: GUID
    subtype: GUID
    frame_size: tuple[int, int]
    frame_rate: tuple[int, int]

    @staticmethod
    @property
    def MAJOR_TYPES() -> MediaTypeMajorTypes: ...
    @staticmethod
    @property
    def VIDEO_FORMATS() -> MediaTypeVideoFormats: ...

class MediaTypeMajorTypes(GuidEnum):
    @property
    def MFMediaType_Audio(self) -> GUID: ...
    @property
    def MFMediaType_Binary(self) -> GUID: ...
    @property
    def MFMediaType_FileTransfer(self) -> GUID: ...
    @property
    def MFMediaType_HTML(self) -> GUID: ...
    @property
    def MFMediaType_Image(self) -> GUID: ...
    @property
    def MFMediaType_Metadata(self) -> GUID: ...
    @property
    def MFMediaType_Protected(self) -> GUID: ...
    @property
    def MFMediaType_Perception(self) -> GUID: ...
    @property
    def MFMediaType_SAMI(self) -> GUID: ...
    @property
    def MFMediaType_Script(self) -> GUID: ...
    @property
    def MFMediaType_Video(self) -> GUID: ...
    @property
    def MFMediaType_Stream(self) -> GUID: ...

class MediaTypeVideoFormats(GuidEnum):
    @property
    def MFVideoFormat_RGB8(self) -> GUID: ...
    @property
    def MFVideoFormat_RGB555(self) -> GUID: ...
    @property
    def MFVideoFormat_RGB565(self) -> GUID: ...
    @property
    def MFVideoFormat_RGB24(self) -> GUID: ...
    @property
    def MFVideoFormat_RGB32(self) -> GUID: ...
    @property
    def MFVideoFormat_ARGB32(self) -> GUID: ...
    @property
    def MFVideoFormat_A2R10G10B10(self) -> GUID: ...
    @property
    def MFVideoFormat_A16B16G16R16F(self) -> GUID: ...
    @property
    def MFVideoFormat_AI44(self) -> GUID: ...
    @property
    def MFVideoFormat_AYUV(self) -> GUID: ...
    @property
    def MFVideoFormat_I420(self) -> GUID: ...
    @property
    def MFVideoFormat_IYUV(self) -> GUID: ...
    @property
    def MFVideoFormat_NV11(self) -> GUID: ...
    @property
    def MFVideoFormat_NV12(self) -> GUID: ...
    @property
    def MFVideoFormat_NV21(self) -> GUID: ...
    @property
    def MFVideoFormat_UYVY(self) -> GUID: ...
    @property
    def MFVideoFormat_Y41P(self) -> GUID: ...
    @property
    def MFVideoFormat_Y41T(self) -> GUID: ...
    @property
    def MFVideoFormat_Y42T(self) -> GUID: ...
    @property
    def MFVideoFormat_YUY2(self) -> GUID: ...
    @property
    def MFVideoFormat_YVU9(self) -> GUID: ...
    @property
    def MFVideoFormat_YV12(self) -> GUID: ...
    @property
    def MFVideoFormat_YVYU(self) -> GUID: ...
    @property
    def MFVideoFormat_P010(self) -> GUID: ...
    @property
    def MFVideoFormat_P016(self) -> GUID: ...
    @property
    def MFVideoFormat_P210(self) -> GUID: ...
    @property
    def MFVideoFormat_P216(self) -> GUID: ...
    @property
    def MFVideoFormat_v210(self) -> GUID: ...
    @property
    def MFVideoFormat_v216(self) -> GUID: ...
    @property
    def MFVideoFormat_v410(self) -> GUID: ...
    @property
    def MFVideoFormat_Y210(self) -> GUID: ...
    @property
    def MFVideoFormat_Y216(self) -> GUID: ...
    @property
    def MFVideoFormat_Y410(self) -> GUID: ...
    @property
    def MFVideoFormat_Y416(self) -> GUID: ...
    @property
    def MFVideoFormat_L8(self) -> GUID: ...
    @property
    def MFVideoFormat_L16(self) -> GUID: ...
    @property
    def MFVideoFormat_D16(self) -> GUID: ...
    @property
    def MFVideoFormat_DV25(self) -> GUID: ...
    @property
    def MFVideoFormat_DV50(self) -> GUID: ...
    @property
    def MFVideoFormat_DVC(self) -> GUID: ...
    @property
    def MFVideoFormat_DVH1(self) -> GUID: ...
    @property
    def MFVideoFormat_DVHD(self) -> GUID: ...
    @property
    def MFVideoFormat_DVSD(self) -> GUID: ...
    @property
    def MFVideoFormat_DVSL(self) -> GUID: ...
    @property
    def MFVideoFormat_H263(self) -> GUID: ...
    @property
    def MFVideoFormat_H264(self) -> GUID: ...
    @property
    def MFVideoFormat_H265(self) -> GUID: ...
    @property
    def MFVideoFormat_H264_ES(self) -> GUID: ...
    @property
    def MFVideoFormat_HEVC(self) -> GUID: ...
    @property
    def MFVideoFormat_HEVC_ES(self) -> GUID: ...
    @property
    def MFVideoFormat_M4S2(self) -> GUID: ...
    @property
    def MFVideoFormat_MJPG(self) -> GUID: ...
    @property
    def MFVideoFormat_MP43(self) -> GUID: ...
    @property
    def MFVideoFormat_MP4S(self) -> GUID: ...
    @property
    def MFVideoFormat_MP4V(self) -> GUID: ...
    @property
    def MFVideoFormat_MPEG2(self) -> GUID: ...
    @property
    def MFVideoFormat_VP80(self) -> GUID: ...
    @property
    def MFVideoFormat_VP90(self) -> GUID: ...
    @property
    def MFVideoFormat_MPG1(self) -> GUID: ...
    @property
    def MFVideoFormat_MSS1(self) -> GUID: ...
    @property
    def MFVideoFormat_MSS2(self) -> GUID: ...
    @property
    def MFVideoFormat_WMV1(self) -> GUID: ...
    @property
    def MFVideoFormat_WMV2(self) -> GUID: ...
    @property
    def MFVideoFormat_WMV3(self) -> GUID: ...
    @property
    def MFVideoFormat_WVC1(self) -> GUID: ...
    @property
    def MFVideoFormat_420O(self) -> GUID: ...
    @property
    def MFVideoFormat_AV1(self) -> GUID: ...
