from typing import Literal
from ._guid import GUID
from ._media_source import MediaSource

__all__ = ["MediaSourceActivate", "enum_device_sources"]

class MediaSourceActivate:
    @property
    def friendly_name() -> str: ...
    @property
    def major_type() -> GUID | None: ...
    @property
    def subtype() -> GUID | None: ...
    @property
    def source_type() -> Literal["video", "audio"]: ...
    @property
    def audio_endpoint_id() -> str | None: ...
    @property
    def video_hardware() -> bool | None: ...
    @property
    def video_symbolic_link() -> str | None: ...
    def open() -> MediaSource: ...

def enum_device_sources(
    device_type: Literal["video", "audio"],
    audio_role: Literal["console", "multimedia", "communications"] | None = None,
) -> list[MediaSourceActivate]: ...
